name: Agent Evals and Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  pipeline:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./demo-agent # If your pyproject.toml is in a subdirectory, change this (e.g., ./my-agent)
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install project dependencies
        run: uv sync --frozen

      - name: Install agents-cli
        run: uv tool install google-agents-cli

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          create_credentials_file: true
          workload_identity_provider: 'projects/1011685515719/locations/global/workloadIdentityPools/github-identity-pool/providers/github-identity-pool'
          project_id: 'gsd-prompt-management'

      - name: Run Evaluations
        run: |
          agents-cli eval generate
          agents-cli eval grade
      
      - name: Set Deployment Target 
        run: |
          agents-cli scaffold enhance -d agent_runtime
      #agents-cli scaffold enhance -d agent_runtime
      - name: Deploy Agent
        # Only deploy on push to main (e.g., after PR merge)
        if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
        run: |
          agents-cli deploy --project gsd-prompt-management --region us-east1